version: '3'
services:
  sqs:
    image: nats:alpine
    ports: 
      - 4222:4222
      - 6222:6222
      - 8222:8222
  main:
    build: ./client
    environment: 
      PORT: 3000
      SQS: 'nats://sqs:4222'
      SERVER_PORT: 7777
      SERVER_HOST: micro
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    depends_on: 
      - sqs
  micro:
    build: ./server
    volumes:
      - ./server:/app
    environment: 
      PORT: 7777
      SQS: 'nats://sqs:4222'
    depends_on: 
      - sqs

